### ISSUE TITLE
Save the model - TypeError: can't pickle Rfft objects

### ISSUE THREAD

**Issue by idansc** [gdlg/pytorch_compact_bilinear_pooling#7] opened 2018-04-14 10:03 UTC
How do you save and load the model, I'm using `torch.save`, which cause the following error:
 ```
File "x/anaconda3/lib/python3.6/site-packages/tor                                                                                                                               ch/serialization.py", line 135, in save
    return _with_file_like(f, "wb", lambda f: _save(obj, f, pickle_module, pickl                                                                                                                               e_protocol))
  File "x/anaconda3/lib/python3.6/site-packages/tor                                                                                                                               ch/serialization.py", line 117, in _with_file_like
    return body(f)
  File "xanaconda3/lib/python3.6/site-packages/tor                                                                                                                               ch/serialization.py", line 135, in <lambda>
    return _with_file_like(f, "wb", lambda f: _save(obj, f, pickle_module, pickl                                                                                                                               e_protocol))
  File "x/anaconda3/lib/python3.6/site-packages/tor                                                                                                                               ch/serialization.py", line 198, in _save
    pickler.dump(obj)
TypeError: can't pickle Rfft objects

```

**Comment by gdlg** [comment] 2018-04-14 11:23
Could you post a small example illustrating the problem?
I think that you are trying to save the model itself rather than model.state_dict().

**Comment by idansc** [comment] 2018-04-14 15:01
You are right, I do save the model and not the parameters. Is it a wrong usage? I think both methods should work. I feel a little safer saving the actual model. It can be used to reconstruct the original model files in case of refactoring.

**Comment by gdlg** [comment] 2018-04-14 21:12
I am not sure whether it is right or not; I have always only saved the parameters. However the problem here lies with the Rfft class in pytorch_fft (and I suspect that all the other FFT variants in pytorch_fft have the same problem); perhaps you should open an issue with [pytorch_fft](https://github.com/locuslab/pytorch_fft). If the issue is fixed in pytorch_fft, it should work without any change to this repo.

**Closed as completed** 2018-04-20 07:19 UTC
